# Generated by Django 3.2.13 on 2023-03-29 04:21

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('grandmaai', '0008_alter_level_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(default='null', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=phone_field.models.PhoneField(default='null', help_text='Contact phone number', max_length=31),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
