# Generated by Django 3.2.13 on 2023-03-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grandmaai', '0009_auto_20230329_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(max_length=31),
        ),
    ]
